# Generated by Django 4.0.1 on 2022-01-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usdt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
