# Generated by Django 4.0.1 on 2022-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_usdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usdt',
            field=models.FloatField(default=100000),
        ),
    ]
