# Generated by Django 4.0.1 on 2022-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0002_rename_amount_wallet_bitcoin_alter_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binance_Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(unique=True),
        ),
    ]
