# Generated by Django 4.0.1 on 2022-01-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0003_binance_candle_alter_order_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_krw', models.FloatField()),
            ],
        ),
    ]
