# Generated by Django 4.0.1 on 2022-01-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0004_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
